name: opa and conftest actions
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  conftest:
    runs-on: ubuntu-latest
    container: openpolicyagent/conftest:latest
    steps:
      - name: debug
        run: find / -name policies 
      - name: conftest verify
        run: conftest verify -p policies/policy1 --output=table
