name: opa and conftest actions
on:
  push:
    branches:
      - main
jobs:
  conftest:
    runs-on: ubuntu-latest
    container: openpolicyagent/conftest:latest
    permissions:
      contents: read
    steps:
      - name: conftest verify
        run: conftest verify -p policies/policy1 --output=table
