name: opa and conftest actions
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  opa:
    runs-on: ubuntu-latest
   
    steps:
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest
      - name: opa test
        run: opa test policies/policy1/policy1.rego policies/policy1/policy1_test.rego -v
